---
abstract: 'free proxy searcher and checker'
author:
  - 'Oleg G <oleg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: proxyhunter
no_index:
  directory:
    - t
    - inc
requires:
  Coro: 2.5
  Coro::PatchSet: 0.07
  DateTime: 0.5
  Getopt::Long: 2.39
  LWP::Protocol::connect: 6.09
  LWP::Protocol::https: 6.02
  LWP::Protocol::socks: 1.7
  LWP::UserAgent: 6.02
  List::MoreUtils: 0.09
  List::Util: 1.3
  Mo: 0.1
  Net::Proxy::Type: 0.08
  Parse::JCONF: 0.02
  Teng: 0.19
  Time::HiRes: 0
  URI: 1.36
resources:
  repository: https://github.com/olegwtf/proxyhunter
version: 0.02
